name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Build compile with Maven
      run: mvn compile
    - name: Run Build review
      run: mvn pmd:pmd
    - name: Run Test with Maven
      run: mvn test
    - name: Run Build package with Maven
      run: mvn package
    - name: upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: ludo-game-jar
        path: target/ludo-game-1.0.0.jar

    